directories:
  output: release-build
  buildResources: build
appId: com.example.ztools
productName: ztools
files:
  - filter:
      - main.js
      - preload.js
      - src/server/**/*
      - dist/**/*
      - devtools/**/*
asar: false
extraResources:
  - from: bin
    to: bin
    filter:
      - '**/*'
win:
  target: nsis
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
publish:
  - provider: github
    owner: zhaichong
    repo: zdevtools
electronVersion: 22.3.27
